default:

  RAW_BUCKET: s3://<your raw data bucket>
  S3_BUCKET: s3://<your processed data bucket>

  COMPUTE_ENV: 'test-env'
  QUEUE_NAME: 'test-queue'

  IMAGE_ID: 'ami-9eb4b1e5'
  INSTANCE_TYPE: 'c4.8xlarge'
  SPOT_PRICE: '0.6'
  TARGET_CAPACITY: 3

  BATCH_SERVICE_ROLE: 
  SPOT_FLEET_ROLE: 

  REFERENCE_SNAPSHOT: 

  KEY_NAME: 
  SECURITY_GROUP: 
  SUBNETS: 
    - 
    - 
    - 
    - 

  STARTUP_CMDS:
    - yum install nano
